// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeNTXxISQeitpPDXLxAVHzcphCi7nwMoQ',
    appId: '1:1021980930147:web:251595e2f8a8a6b3e8c856',
    messagingSenderId: '1021980930147',
    projectId: 'calender-scheduler-af89-e006d',
    authDomain: 'calender-scheduler-af89-e006d.firebaseapp.com',
    storageBucket: 'calender-scheduler-af89-e006d.appspot.com',
    measurementId: 'G-T7L8YJBW2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpiS-VhB_nCCVpwDGr3Pob9U9p6q9NboI',
    appId: '1:1021980930147:android:96be68830708e646e8c856',
    messagingSenderId: '1021980930147',
    projectId: 'calender-scheduler-af89-e006d',
    storageBucket: 'calender-scheduler-af89-e006d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBg98qa9R4Qbx5-a8Nrfzdhq6yQ063dUs',
    appId: '1:1021980930147:ios:cbe4313d378ead39e8c856',
    messagingSenderId: '1021980930147',
    projectId: 'calender-scheduler-af89-e006d',
    storageBucket: 'calender-scheduler-af89-e006d.appspot.com',
    iosBundleId: 'com.example.calenderScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBg98qa9R4Qbx5-a8Nrfzdhq6yQ063dUs',
    appId: '1:1021980930147:ios:99542d48c2545deee8c856',
    messagingSenderId: '1021980930147',
    projectId: 'calender-scheduler-af89-e006d',
    storageBucket: 'calender-scheduler-af89-e006d.appspot.com',
    iosBundleId: 'com.example.calenderScheduler.RunnerTests',
  );
}
